# Generated by Django 3.1.1 on 2020-09-16 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('cast', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('BENGALI', 'Bengali'), ('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu'), ('KANNADA', 'Kannada')], max_length=10)),
                ('run_length', models.IntegerField(blank=True, help_text='Enter run length in minutes', null=True)),
                ('certificate', models.CharField(choices=[('U', 'U'), ('UA', 'U/A'), ('A', 'A'), ('R', 'R')], max_length=2)),
                ('popularity_index', models.IntegerField(blank=True, null=True, unique=True)),
                ('trailer', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Waves Cinema', max_length=50)),
                ('city', models.CharField(choices=[('BANGALORE', 'Bangalore'), ('CHENNAI', 'Chennai'), ('DELHI', 'Delhi'), ('HYDERABAD', 'Hyderabad'), ('KOLKATA', 'Kolkata'), ('MUMBAI', 'Mumbai')], max_length=9)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=3, null=True)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('', 'Select'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=8)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.show')),
            ],
            options={
                'unique_together': {('no', 'show')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card')], default='Credit Card', max_length=11)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seat')),
            ],
            options={
                'unique_together': {('seat', 'booking')},
            },
        ),
    ]
